name: finger_painter
description: Painting package that let you finger paint with different brushes and
  different blend modes. The result can be read as a bitmap or list of Points to be
  used ie on a Map.
version: 0.9.1
homepage: https://github.com/alnitak/finger_painter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
